---
title: "Part 6 / Part 10"
author: "Brendan Callender"
date: "5/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(readxl)
library(leaps)
library(car)
```


```{r}
realestate <- read_excel("SLO_Real_Estate_Feb-Apr2022.xlsx")

realestate_clean <- realestate %>%
  filter(LotSize != 416869 & LotSize != 108900 & LotSize != 84071)

realestate_clean <- realestate_clean %>%
  mutate(HomeTypeNew = 
           case_when(HomeType == "Condominium" ~ "Condo", 
             HomeType == "SingleFamilyResidence" ~ "SingleFam",
             HomeType == "ManufacturedHome" ~ "Manufactured",
             TRUE ~ "Other")) 

realestate_clean$Cooling = factor(realestate_clean$Cooling)
realestate_clean$Heating = factor(realestate_clean$Heating)
realestate_clean$HomeTypeNew = factor(realestate_clean$HomeTypeNew)
realestate_clean$Pool = factor(realestate_clean$Pool)
```



```{r}
n <- 141
numtrain = ceiling(.8*n)
set.seed(678)
train_ind = sample(n, numtrain)
traindata = realestate_clean[train_ind, ]
testdata = realestate_clean[-train_ind, ]
set.seed(NULL)
```



```{r}
full.model <- lm(SoldPrice~., data = traindata)
summary(full.model)
```

```{r}
best.sub <- summary(regsubsets(formula(full.model), data=traindata, method = "exhaustive", nbest = 2))

```


```{r}
n = nrow(realestate) #sample size
p<-c(2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9) #number of coeffs ***SEE REMARK BELOW***

#Compute and Store Quantities of interest (SSE,s,Rsq,AIC,BIC,Cp)
SSE<-best.sub$rss             #SSE 
s<-sqrt(SSE/(n-p))            #s
Rsq<-best.sub$rsq             #R-squared 
Rsq.adj<-best.sub$adjr2       #R-squared adjusted
BIC<-n*log(SSE/n) + p*log(n)  #BIC
AIC<- n*log(SSE/n) + 2*p      #AIC
Cp<-best.sub$cp               #Mallow's Cp
bs<- data.frame(best.sub$outmat, p=p, Cp, AIC, BIC, Rsq, Rsq.adj, s)
```

```{r}
bs %>%
  arrange(BIC)
```

```{r}
fit.one <- lm(I(log(SoldPrice))~Sqft+LotSize+HomeType, data = traindata)

summary(fit.one)
```
```{r}
traindata %>%
  arrange(desc(LotSize)) %>%
  filter()
```



```{r}
plot(resid(lm(I(log(SoldPrice))~LotSize + HomeType, data = traindata))~resid(lm(Sqft ~ LotSize + HomeType, data = traindata)))
```


```{r}
plot(resid(lm(I(log(SoldPrice))~Sqft + HomeType, data = traindata))~resid(lm(I(log(LotSize)) ~ YearBuilt + Sqft + HomeType, data = traindata)))

plot(resid(lm(I(log(SoldPrice))~Sqft + HomeType, data = traindata))~resid(lm(LotSize ~ YearBuilt + Sqft + HomeType, data = traindata)))

```

```{r}
plot(fit.one)
```



```{r}
fit.two <- lm(I(sqrt(SoldPrice))~Sqft+YearBuilt+HomeType, data = realestate)

summary(fit.two)
```

```{r}
plot(resid(lm(I(log(SoldPrice))~YearBuilt + HomeType, data = realestate))~resid(lm(Sqft ~ YearBuilt + HomeType, data = realestate)))
```


```{r}
plot(resid(lm(I(log(SoldPrice))~Sqft + HomeTypeNew, data = traindata))~resid(lm(YearBuilt ~ Sqft + HomeTypeNew, data = traindata)))
```


```{r}
plot(fit.two)
```

```{r}
shapiro.test(fit.two$residuals)
```


```{r}
realestate %>%
  ggplot() +
  geom_point(aes(y = SoldPrice, x = Sqft, col = HomeType))
```

```{r}

traindata %>%
  ggplot() +
  geom_point(aes(y = SoldPrice, x = Sqft, col = HomeTypeNew))
  
```

```{r}
realestate %>%
  group_by(HomeTypeNew) %>%
  summarise(n = n())
  
```



```{r}
fit.three <- lm(I((SoldPrice))~Sqft+HomeTypeNew+YearBuilt, data = realestate)

summary(fit.three)
```



```{r}
plot(resid(lm(I(log(SoldPrice))~YearBuilt + HomeTypeNew, data = realestate))~resid(lm(Sqft ~ YearBuilt + HomeTypeNew, data = realestate)))
```




```{r}
plot(resid(lm(I(log(SoldPrice))~Sqft + HomeTypeNew, data = realestate))~resid(lm(YearBuilt ~ Sqft + HomeTypeNew, data = realestate)))
```


```{r}
plot(fit.three)
```

```{r}
full.model2 <- lm(I(log(SoldPrice)) ~ Sqft + YearBuilt + HomeTypeNew + Bed + Bath + Parking + Cooling + Heating + Pool, data = realestate)
```



```{r}
best.sub2 <- summary(regsubsets(formula(full.model2), data=realestate, method = "exhaustive", nbest = 2))

```





```{r}
n = nrow(realestate) #sample size
p<-c(2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9) #number of coeffs ***SEE REMARK BELOW***

#Compute and Store Quantities of interest (SSE,s,Rsq,AIC,BIC,Cp)
SSE<-best.sub2$rss             #SSE 
s<-sqrt(SSE/(n-p))            #s
Rsq<-best.sub2$rsq             #R-squared 
Rsq.adj<-best.sub2$adjr2       #R-squared adjusted
BIC<-n*log(SSE/n) + p*log(n)  #BIC
AIC<- n*log(SSE/n) + 2*p      #AIC
Cp<-best.sub2$cp               #Mallow's Cp
bs2<- data.frame(best.sub2$outmat, p=p, Cp, AIC, BIC, Rsq, Rsq.adj, s)
```


```{r}
bs2 %>%
  arrange(BIC)
```

```{r}
fit.four <- lm(log(SoldPrice) ~ Sqft + HomeTypeNew + I(Bath - mean(realestate$Bath)), data = realestate)
```



```{r}
plot(fit.four)
```



```{r}

plot(resid(lm(I(log(SoldPrice))~Sqft + HomeTypeNew, data = realestate))~resid(lm(Bath ~ Sqft + HomeTypeNew, data = realestate)))

```


```{r}
plot(resid(lm(I(log(SoldPrice))~YearBuilt + HomeTypeNew, data = realestate))~resid(lm(Sqft ~ YearBuilt + HomeTypeNew, data = realestate)))
```


```{r}
realestate %>%
  ggplot() +
  geom_point(aes(x = Sqft, y = Bath))
```

```{r}
vif(fit.four)
```


```{r}
vif(fit.three)
```


```{r}
boxCox(lm(SoldPrice~Sqft+YearBuilt+HomeTypeNew, data = realestate))
```

```{r}
fit.five = lm(lm(I(sqrt(SoldPrice))~Sqft+LotSize+HomeTypeNew, data = traindata))

summary(fit.five)
```


```{r}
plot(fit.five)
```


```{r}

plot(resid(lm(I(sqrt(SoldPrice))~Sqft + HomeTypeNew, data = realestate))~resid(lm(YearBuilt ~ Sqft + HomeTypeNew, data = realestate)))
```



```{r}
plot(resid(lm(I(sqrt(SoldPrice))~YearBuilt + HomeTypeNew, data = realestate))~resid(lm(Sqft ~ YearBuilt + HomeTypeNew, data = realestate)))
```


```{r}
realestate %>%
  ggplot() +
  geom_boxplot(aes(x = HomeTypeNew, y = SoldPrice))
```



```{r}
fit.three <- lm(SoldPrice~Sqft+LotSize+HomeType, data = realestate)
```


```{r}
boxCox(fit.three)

```

```{r}
plot(fit.three)
```




```{r}
full <- read_excel("SLO_Real_Estate_Feb-Apr2022.xlsx")
n <- 144
numtrain = ceiling(.8*n)
set.seed(678)
train_ind = sample(n, numtrain)
bren = full[train_ind, ]
bren <- bren %>%
  mutate(HomeTypeNew = 
           case_when(HomeType == "Condominium" ~ "Condo", 
             HomeType == "SingleFamilyResidence" ~ "SingleFam",
             HomeType == "ManufacturedHome" ~ "Manufactured",
             TRUE ~ "Other")) 
```

```{r}
bren.model <- lm(SoldPrice ~ Sqft + LotSize + HomeTypeNew, data = bren)
```

```{r}
plot(resid(lm(SoldPrice ~ Sqft + HomeTypeNew, data = bren))~resid(lm(LotSize ~ Sqft + HomeTypeNew, data = bren)), xlab = "LotSize | Others", ylab = "SoldPrice | Others")
```

```{r}
plot(resid(lm(SoldPrice ~ Sqft + HomeTypeNew, data = traindata))~resid(lm(LotSize ~ Sqft + HomeTypeNew, data = traindata)), xlab = "LotSize | Others", ylab = "SoldPrice | Others")
```
```{r}
fit.three <- lm(SoldPrice ~ Sqft + LotSize + HomeTypeNew, data = traindata)
plot(fit.three)
```


